title: CTCA Quick-Start
description: >-
  A practical guide to CT Coronary Angiography for core radiology trainees.
theme: minima

url: ""

exclude:
  - raw/
  - Gemfile
  - Gemfile.lock
  - "*.py"
  - "*.sh"
  - _config_pages.yml

plugins:
  - jekyll-seo-tag
  - jekyll-tabs
